= poly-synth-envelope branch
This branch is made in order to add a standardized envelope to the *SynthVoice* abstract class, which will be inherited by
any subclass.

It is necessay that the individual synth voices have an internal envelope (like an ADSR envelope) because, otherwise, the
polyphonic synthesizer using those voices will sound bad when multiple notes are playing at the same time.

Forcing each single voice to have some kind of volume envelope gives a much nicer sound, a more predictable result.

The volume will be provided by any subclass of *SynthVoice* and it can be any type of envelope (not just ADSR) so the 
design is flexible.

In order to obtain this design we use the following:
* *interface EnvelopeMultiplier*: this is the template for any envelope
[,ts]
----
export interface EnvelopeMultiplier extends Emitter, Receiver
{
    triggerAttack(): void;
    triggerRelease(): void;
    getFinsihTime(): number;
}`
----
* *export abstract class SynthVoice<N extends Note> implements Emitter*: this represents a sungle synth voice that has
an internal envelope
[,ts]
----
export abstract class SynthVoice<N extends Note> implements Emitter
{
    // ...
    
    protected abstract startSignal(note: N): void;
    protected abstract releaseSignal(): void;
    protected abstract getEnvelopeMultiplier(): EnvelopeMultiplier; // this is the method that must return an envelope

    // ...
}
----

= React + TypeScript + Vite

This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.

Currently, two official plugins are available:

* https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react[@vitejs/plugin-react] uses https://babeljs.io/[Babel] for Fast Refresh
* https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react-swc[@vitejs/plugin-react-swc] uses https://swc.rs/[SWC] for Fast Refresh

== Expanding the ESLint configuration

If you are developing a production application, we recommend updating the configuration to enable type-aware lint rules:

[,js]
----
export default tseslint.config([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      // Other configs...

      // Remove tseslint.configs.recommended and replace with this
      ...tseslint.configs.recommendedTypeChecked,
      // Alternatively, use this for stricter rules
      ...tseslint.configs.strictTypeChecked,
      // Optionally, add this for stylistic rules
      ...tseslint.configs.stylisticTypeChecked,

      // Other configs...
    ],
    languageOptions: {
      parserOptions: {
        project: ['./tsconfig.node.json', './tsconfig.app.json'],
        tsconfigRootDir: import.meta.dirname,
      },
      // other options...
    },
  },
])
----

You can also install https://github.com/Rel1cx/eslint-react/tree/main/packages/plugins/eslint-plugin-react-x[eslint-plugin-react-x] and https://github.com/Rel1cx/eslint-react/tree/main/packages/plugins/eslint-plugin-react-dom[eslint-plugin-react-dom] for React-specific lint rules:

[,js]
----
// eslint.config.js
import reactX from 'eslint-plugin-react-x'
import reactDom from 'eslint-plugin-react-dom'

export default tseslint.config([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      // Other configs...
      // Enable lint rules for React
      reactX.configs['recommended-typescript'],
      // Enable lint rules for React DOM
      reactDom.configs.recommended,
    ],
    languageOptions: {
      parserOptions: {
        project: ['./tsconfig.node.json', './tsconfig.app.json'],
        tsconfigRootDir: import.meta.dirname,
      },
      // other options...
    },
  },
])
----
