= poly-synth-envelope branch
This branch is made in order to add a standardized envelope to the *SynthVoice* abstract class, which will be inherited by
any subclass.

It is necessay that the individual synth voices have an internal envelope (like a ADSR envelope) because, otherwise, the polyphonic synthesizer using those voice will sound bad when multple notes are playing at the same time.

Forcing that each single voice has some kind of volume envelope gives a much nicer sound, a more predictable result.

The actual subclass will provide the volume envelope, so the design is flexible.

= React + TypeScript + Vite

This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.

Currently, two official plugins are available:

* https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react[@vitejs/plugin-react] uses https://babeljs.io/[Babel] for Fast Refresh
* https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react-swc[@vitejs/plugin-react-swc] uses https://swc.rs/[SWC] for Fast Refresh

== Expanding the ESLint configuration

If you are developing a production application, we recommend updating the configuration to enable type-aware lint rules:

[,js]
----
export default tseslint.config([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      // Other configs...

      // Remove tseslint.configs.recommended and replace with this
      ...tseslint.configs.recommendedTypeChecked,
      // Alternatively, use this for stricter rules
      ...tseslint.configs.strictTypeChecked,
      // Optionally, add this for stylistic rules
      ...tseslint.configs.stylisticTypeChecked,

      // Other configs...
    ],
    languageOptions: {
      parserOptions: {
        project: ['./tsconfig.node.json', './tsconfig.app.json'],
        tsconfigRootDir: import.meta.dirname,
      },
      // other options...
    },
  },
])
----

You can also install https://github.com/Rel1cx/eslint-react/tree/main/packages/plugins/eslint-plugin-react-x[eslint-plugin-react-x] and https://github.com/Rel1cx/eslint-react/tree/main/packages/plugins/eslint-plugin-react-dom[eslint-plugin-react-dom] for React-specific lint rules:

[,js]
----
// eslint.config.js
import reactX from 'eslint-plugin-react-x'
import reactDom from 'eslint-plugin-react-dom'

export default tseslint.config([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      // Other configs...
      // Enable lint rules for React
      reactX.configs['recommended-typescript'],
      // Enable lint rules for React DOM
      reactDom.configs.recommended,
    ],
    languageOptions: {
      parserOptions: {
        project: ['./tsconfig.node.json', './tsconfig.app.json'],
        tsconfigRootDir: import.meta.dirname,
      },
      // other options...
    },
  },
])
----
